name: Build docker image and run tests

# Define the events that trigger this workflow
on:
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker container image
        run: docker build -t actiontest .
        
      - name: Run docker image and launch shell
        run: docker run -d  --name testcontainer -v "$(pwd):/tests"  actiontest:latest

      - name: check if container is running
        run: docker ps -a

      - name: Run tests
        run: docker exec testcontainer python -m pytest . --html=report.html --self-contained-html
        
      - name: Upload raw report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report.html
